### ISSUE TITLE
Unable to run the project

### ISSUE THREAD

**Issue by texyz** [erikmartens/NearbyWeather#157]
Project failed to run
<img width="1393" alt="Screenshot 2020-05-16 at 04 00 18" src="https://user-images.githubusercontent.com/34765619/82108879-d9197900-9729-11ea-83ee-2d1ebc5eed95.png">

**Comment by erikmartens** [comment]
Hello @texyz, thanks for checking out the project. Before I can help with the issue, I need a little more information. Have you followed all the steps to setup the project as outlined in the readme? It seems you have not yet installed the pods.

**Comment by texyz** [comment]
<img width="712" alt="Screenshot 2020-05-16 at 18 12 44" src="https://user-images.githubusercontent.com/34765619/82125901-f2a9d780-97a0-11ea-97aa-9254514bb23e.png">
When i tried to install the pods i kept on getting the above

**Comment by texyz** [comment]
<img width="868" alt="Screenshot 2020-05-16 at 18 23 28" src="https://user-images.githubusercontent.com/34765619/82126107-65678280-97a2-11ea-8fc7-b499ff99e900.png">

After updating the pods

**Comment by erikmartens** [comment]
> When i tried to install the pods i kept on getting the above

@texyz have you tried running `pod repo update` before running `pod install`?

**Comment by erikmartens** [comment]
Hope this has solved your issue. I'm closing this now due to inactivity but feel free to re-open if you keep having issues.
