### ISSUE TITLE
Temperature on App Icon via Badge

### ISSUE THREAD

**Issue by erikmartens** [erikmartens/NearbyWeather#30]
- [x] Badge Service
- [x] PermissionsManager?
- [x] Bookmarked locations can show temp via icon badge (selecting one disables previous, if any)
- [x] Background refresh, so app does not have to be opened to refresh data
- [x] Local push notification when temp goes below/above 0° as badge number is unsigned

**Comment by lprokein** [comment]
Hey @erikmartens, can I implement this one?

**Comment by erikmartens** [comment]
Hi @lprokein, of course! Thanks for taking part in this app :)

**Comment by lprokein** [comment]
Hi, I was thinking about alternative way of indicating temperature sign. It is possible to set alternative app icon starting from iOS 10.3 - so how about changed app icon when supported as well?

<img src="https://user-images.githubusercontent.com/22453682/47270303-6571b300-d56a-11e8-9765-96c295405987.png" width="300">

<img src="https://user-images.githubusercontent.com/22453682/47270304-6571b300-d56a-11e8-8292-dc2ec9df8a08.png" width="300">

**Comment by erikmartens** [comment]
Hey @lprokein, that's a great idea. I might tweak the logo before releasing the update, but I really like the concept!

**Comment by lprokein** [comment]
Hi, I tried to implement it but it won't be possible to do it in background. The thing is that when you perform alternative app icon change it opens alert as confirmation. It works fine when app is in foreground but when data is updating by background fetch it wont update icon. Whole alternative-icon logic is in my last commit https://github.com/erikmartens/NearbyWeather/pull/47/commits/c9e5e2761e3cd5b12c9a0ab1e257841e55c26a02 so try it and decide whether use it or now. Btw that iOS background fetch works really weird, for me it started to fetch data after one or two days. But it's the only option without using remote push-notifications to wake the app.

**Comment by erikmartens** [comment]
Hey @lprokein, yes, background activity is quite limited by Apple. An app that uses too much time, will get limited over time. It's not an exact science and Apple doesn't really disclose any details as far as I am aware. But for a free App like NearbyWeather that is fine. 

Regarding the switch of the app icon, I'd suggest just switching to a local Notification announcing the switch from positive from negative (or vice versa). Otherwise it might be confusing, since the app icon will be showing the wrong information at times...

Anyway I'll get to reviewing your PR today 😊 After I'm done, you could still make those changes and then the final review should not take long. In the meantime I can make some cleanups and prepare the app for the next release :+1:
