### ISSUE TITLE
Minor Bugfixes

### ISSUE THREAD

**Issue by erikmartens** [erikmartens/NearbyWeather#38]
- [x] Disable Dark Mode via plist entry
- [x] Settings Distance/Speed Unit Cell shows disclosure indidicator [_iOS 9 (& iOS 10?) only_]
- [x] MapView `UIBarButtonItems` show weird line [_iOS 9 (& iOS 10?) only_]
- [x] OpenWeatherMap-Button in detail view does not work for bookmarked locations

**Comment by roselloryan** [comment]
Hi Erik, 
I'm trying to learn how to contribute to open source projects. Seems like you created this project for that reason, so I'm going to give it a try. I started with a minor bug fix for the UIBarButtonItems on the mapView. Hope that's ok. Thank you.

**Comment by erikmartens** [comment]
@roselloryan 
Hey Ryan,
indeed I created this project to allow others to contribute to an app, which is live on the App Store. All contributions are welcome and once reviewed, they'll be merged. Eventually, there will be CI in place to help with the reviews. I will look at your work over the next couple of days. 
Thanks for helping out and keep 'em coming!
