### ISSUE TITLE
Build Swift Lint

### ISSUE THREAD

**Issue by erikmartens** [erikmartens/NearbyWeather#46]

**Comment by pylapp** [comment]
Hi @erikmartens!

I have seen this issue planned for version 2.1, and I work on it on my fork.
I succeeded in integrating _SwiftLint_ in the project (file of rules and _Xcode_ build phase), and defined common rules.

However I have an important question to ask you, which might have a huge impact on the source files content (syntax, not features nor algorithms): which rules do you want to apply?
With the SwiftLint integration, warnings are risen and errors are thrown, that is the reason why we/you should choose rules to apply... and fix alerts :)

I can clean up the sources following these alerts, based on the rules file, but want to know your specifications. For information my working branch has been directly created from your current _master_ branch to avoid to have big pull requests with to much commits related to other PR ^^'

What is your point of view?

Cheers!

_You can have a look on https://github.com/pylapp/NearbyWeather/blob/46-build-swiftlint/.swiftlint.yml_
